### ISSUE TITLE
Error configuring the extension when defining two default languages.

### ISSUE THREAD

**Issue by iichernenko** [Crissium/zim-multilingual-spellchecker#1]
Hi, I tried to use your extension.
I got an error:

![изображение](https://github.com/Crissium/zim-multilingual-spellchecker/assets/97665383/50cff03a-a263-4c2c-bb07-216421e218ab)

**Comment by Crissium** [comment]
Strange. Could you please share your notebook's `.zim` file (located in the top level directory of the notebook)?

Mine looks like this:

```
[Notebook]
version=0.4
name=Notes
interwiki=
home=Home
icon=
document_root=
short_links=False
shared=True
endofline=unix
disable_trash=False
default_file_format=zim-wiki
default_file_extension=.txt
notebook_layout=files

[JournalPlugin]
namespace=Journal
granularity=Day

[SpellPlugin]
languages=en_GB fr_FR
```
