### ISSUE TITLE
Not spellchecking live

### ISSUE THREAD

**Issue by sojusnik** [Crissium/zim-multilingual-spellchecker#2]
The spellchecking isn't working live, i.e. after finishing a word or writing a new sentence/paragraph, but only after reloading page or reenabling spellchecking.

Is this by design?

Happens on Zim 0.75.2 under Ubuntu 23.10

**Comment by Crissium** [comment]
No, it's not. Such behaviour probably indicates a bug. I have used Zim for years, from the original pre-Python 3 version to this day, and I must say the original spellchecker sometimes also has this problem. Restarting usually makes it disappear. But with my new plugin this has never happened. I am on Zim 0.75.1 on Debian 12.

Does restarting solve the problem? If not, does the original spellchecker have it?

**Comment by Crissium** [comment]
Perhaps I get what you meant… If you corrected the spelling manually (not by selection a suggestion), the red underline won't go away. This is indeed a serious bug and I will look into it later.

**Comment by sojusnik** [comment]
> Perhaps I get what you meant… If you corrected the spelling manually (not by selecting a suggestion), the red underline won't go away. This is indeed a serious bug and I will look into it later.

I've meant something else, namely that every word/sentence that was typed wasn't spell checked immediately, but surprisingly with the last commit it now works fine! Thanks!

**Comment by Crissium** [comment]
> I finally got what you meant by 'not checking live.' Turns out that after changing pages the spellchecker seems to have 'died.' This is a critical bug and is probably caused by my wrong usage of GTK (I have very limited experience with the library). At the moment I worked around the bug with a very ugly hack. Will check it later when I have more time. #3

**Comment by Crissium** [comment]
Hello! After some very busy months and a big move abroad I finally found some time to fix this project up. Could you verify if the latest commit fixed the problem?

**Comment by sojusnik** [comment]
Seems to work fine now, thanks!
