### ISSUE TITLE
 configuration of language codes sometimes cleared

### ISSUE THREAD

**Issue by Simplenuity** [Crissium/zim-multilingual-spellchecker#4]
@Crissium, the following is more a heads-up than a bug report as I'm still not able to reproduce it.
When starting Zim and opening one of my notebooks I encountered on several occasions that the field for the language codes (two languages in my case) got cleared and consequentially the plugin is throwing an error message.

**Comment by Crissium** [comment]
Sorry I didn't get back to you days ago and thanks for debugging it for me!

Yes 'languages' is a notebook property. Checking for multiple languages incurs significant performance penalty and the long list of (mostly irrelevant) suggestions could be annoying, so the user should only set the relevant languages for each notebook, for example I've got a technical notebook where I only write in English and a personal one where I use all languages I know. I'll add a note about that later.
